protected/controllers/SiteController.php
<?php

class SiteController extends Controller 
{
	public function actionIndex() 
	{				
		$this->render('index');
	}
	
	public function actionIndice() 
	{
		$paginas = Pagina::model()->findAll(array('order' => 'titulo'));
		
		$this->render('indice', array(
			'paginas' => $paginas
		));
	}
		
	public function actionPagina($id) 
	{
		$pagina = Pagina::model()->findByAttributes(array('nome' => $id));
		
		if ($pagina === null)
			throw new CHttpException(404, 'A página solicitada não existe.');

		$anuncios = Anuncio::model()->with(array(
			'pagina' => array(
				'condition' => 'nome = :nome',
				'params' => array(
					':nome' => $pagina->nome
				)
			)
		))->findAll(array('order' => 'nome'));		
		
		$this->render('pagina', array(
			'pagina' => $pagina,
			'anuncios' => $anuncios
		));
	}
	
	public function actionConheca() 
	{
		$this->render('conheca');
	}
	
	public function actionUteis() 
	{
		$this->render('uteis');
	}
	
	public function actionAnuncie() 
	{		
		$model = new ContatoForm('anuncie');
		if(isset($_POST['ContatoForm']))
		{
			$model->attributes=$_POST['ContatoForm'];
			if($model->validate())
			{
				$from = Yii::app()->params['emailContato'];
				$headers  = "MIME-Version: 1.0\r\n";
				$headers .= "Content-Type: text/html; charset=utf-8\r\n";
				$headers .= "From: {$from}\r\n";
				$headers .= "Reply-To: {$model->email}\r\n";
				$headers .= "Return-Path: {$from}\r\n";
				$body  = "<style>";
				$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
				$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
				$body .= "th { width: 140px; text-align: left; }";
				$body .= "</style>";
				$body .= "<table>";
				$body .= "<tr>";
				$body .= "<th>{$model->getAttributeLabel('nome')}:</th>";
				$body .= "<td>{$model->nome}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('area')}:</th>";
				$body .= "<td>{$model->area}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('contato')}:</th>";
				$body .= "<td>{$model->contato}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('telefone')}:</th>";
				$body .= "<td>{$model->telefone}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('email')}:</th>";
				$body .= "<td>{$model->email}</td>";
				$body .= "</tr>";
				$body .= "</table>";
				
				mail($from, 'Site > Anuncie', $body, $headers, "-r" . $from);
				Yii::app()->user->setFlash('contatoForm', 'Obrigado por entrar em contato. Responderemos sua mensagem o mais breve possível.');
				$this->refresh();
			}
		}
		
		$this->render('anuncie', array(
			'model' => $model
		));
	}

	public function actionCadastro() 
	{		
		$model = new ContatoForm('cadastro');
		if(isset($_POST['ContatoForm']))
		{
			$model->attributes=$_POST['ContatoForm'];
			if($model->validate())
			{
				$from = Yii::app()->params['emailContato'];
				$headers  = "MIME-Version: 1.0\r\n";
				$headers .= "Content-Type: text/html; charset=utf-8\r\n";
				$headers .= "From: {$from}\r\n";
				$headers .= "Reply-To: {$model->email}\r\n";
				$headers .= "Return-Path: {$from}\r\n";
				$body  = "<style>";
				$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
				$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
				$body .= "th { width: 140px; text-align: left; }";
				$body .= "</style>";
				$body .= "<table>";
				$body .= "<tr>";
				$body .= "<th>{$model->getAttributeLabel('nome')}:</th>";
				$body .= "<td>{$model->nome}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('area')}:</th>";
				$body .= "<td>{$model->area}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('contato')}:</th>";
				$body .= "<td>{$model->contato}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('telefone')}:</th>";
				$body .= "<td>{$model->telefone}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('email')}:</th>";
				$body .= "<td>{$model->email}</td>";
				$body .= "</tr>";
				$body .= "</table>";
				
				mail($from, 'Site > Cadastro', $body, $headers, "-r" . $from);
				Yii::app()->user->setFlash('contatoForm', 'Obrigado por entrar em contato. Responderemos sua mensagem o mais breve possível.');
				$this->refresh();
			}
		}
		
		$this->render('cadastro', array(
			'model' => $model
		));
	}
	
	public function actionContato() 
	{		
		$model = new ContatoForm('contato');
		if(isset($_POST['ContatoForm']))
		{
			$model->attributes=$_POST['ContatoForm'];
			if($model->validate())
			{
				$from = Yii::app()->params['emailContato'];
				$headers  = "MIME-Version: 1.0\r\n";
				$headers .= "Content-Type: text/html; charset=utf-8\r\n";
				$headers .= "From: {$from}\r\n";
				$headers .= "Reply-To: {$model->email}\r\n";
				$headers .= "Return-Path: {$from}\r\n";
				$body  = "<style>";
				$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
				$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
				$body .= "th { width: 140px; text-align: left; }";
				$body .= "</style>";
				$body .= "<table>";
				$body .= "<tr>";
				$body .= "<th>{$model->getAttributeLabel('nome')}:</th>";
				$body .= "<td>{$model->nome}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('contato')}:</th>";
				$body .= "<td>{$model->contato}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('telefone')}:</th>";
				$body .= "<td>{$model->telefone}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('email')}:</th>";
				$body .= "<td>{$model->email}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('mensagem')}:</th>";
				$body .= "<td>{$model->mensagem}</td>";
				$body .= "</tr>";
				$body .= "</table>";
				
				mail($from, 'Site > Contato', $body, $headers, "-r" . $from);
				Yii::app()->user->setFlash('contatoForm', 'Obrigado por entrar em contato. Responderemos sua mensagem o mais breve possível.');
				$this->refresh();
			}
		}
		
		$this->render('contato', array(
			'model' => $model
		));
	}
	
	public function actionError() 
	{
		if ($error = Yii::app()->errorHandler->error) 
		{
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

protected/views/layouts/_footer.php
	<?php if ($this->action->id !== 'index') : ?>
	<!-- inicia rodape -->
	<div id="container-rodape">
		<div id="container">	
			<p><?php echo CHtml::encode(Yii::app()->name); ?> - Todos os direitos reservados.</p>
		</div>
	</div>
	<?php endif; ?>
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/main.js"></script>
	<script src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-507491830bdfdb50"></script>
</body>
</html>

protected/views/layouts/_header.php
<!DOCTYPE html>
<html lang="pt-br">
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="pt-br"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="pt-br">        <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="pt-br">               <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt-br">                      <!--<![endif]-->
<head>
	<meta charset="utf-8">	
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title><?php echo CHtml::encode(Yii::app()->name) . ($this->pageTitle ? ' / ' . CHtml::encode($this->pageTitle) : ''); ?></title>
  <meta name="description" content="<?php echo Yii::app()->params['metaDescription']; ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	
	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-57307723-1', 'auto');
	ga('send', 'pageview');
	</script>
	
	<?php Yii::app()->clientScript->registerCoreScript('jquery'); ?>

</head>
<body class="page-<?php echo $this->action->id; ?>">

protected/views/layouts/_topo.php
<div id="container-topo">
	<div id="container">
		<div class="topo-esquerdo">
			<!-- inicio menu superior -->
			
			<?php $this->widget('application.widgets.Menu', array(
				'items' => array(
					array(
						'label' => 'Conheça o FoneFácil',
						'url' => Yii::app()->createUrl('/site/conheca'),
						'itemOptions' => array('class' => 'first')
					),
					array(
						'label' => 'Quero Anunciar',
						'url' => Yii::app()->createUrl('/site/anuncie')
					),
					array(
						'label' => 'Cadastre sua empresa',
						'url' => Yii::app()->createUrl('/site/cadastro')
					),
					array(
						'label' => 'Contato',
						'url' => Yii::app()->createUrl('/site/contato'),
						'itemOptions' => array('class' => 'last')
					)
				),
				'htmlOptions' => array('class' => 'menu')
			)); ?>

			<!-- final menu superior -->
			<div class="clear"></div>
				<div class="conteudo-topo">
					<h1><img class="img-1" src="<?php echo Yii::app()->request->baseUrl; ?>/img/logo.jpg" title="FONEFÁCIL - Catálogo Comercial de Salto" alt="FONEFÁCIL - Catálogo Comercial de Salto" /></h1>
						<!-- inicio da pesquisa -->
						<div class="pesquisa">
							<small>Escolha o Ramo de Atividade</small>

							<?php echo CHtml::dropDownList('search-pagina', 
								$this->action->id === 'pagina' ? $this->createUrl('pagina', array('id' => Yii::app()->request->getParam('id'))) : '', 
									CHtml::listData(Pagina::model()->findAll(array('order' => 'nome')), 'url', 'titulo'), 
										array('empty' => 'busca rápida')); ?>

							<p>Encontre o profissional ou comércio que <br /> procura de maneira rápida e simples.</p>
							<img class="img-3" src="<?php echo Yii::app()->request->baseUrl; ?>/img/icone-busca.png" />
						</div>
						<!-- final da pesquisa -->
					<div class="clear"></div>
				</div>
			<div class="clear"></div>
				<!-- inicio do menu inferior -->
				<?php $this->widget('application.widgets.Menu', array(
					'items' => array(
						array(
							'label' => 'Índice Anunciante',
							'url' => Yii::app()->createUrl('/site/indice'),
							'itemOptions' => array('class' => 'first')
						),
						array(
							'label' => 'Telefone Úteis',
							'url' => Yii::app()->createUrl('/site/uteis')
						),
						array(
							'label' => 'Guia Unimed',
							'url' => Yii::app()->createUrl('#'),
							'itemOptions' => array('class' => 'last')
						)
					),
					'htmlOptions' => array('class' => 'menu menu-inf')
				)); ?>
				<!-- final do menu inferior -->
		</div>
		<!-- final do conteudo do topo esquerdo-->
		<!-- inicio do conteudo topo direito-->
		<div class="topo-direito">
			<img class="img-2" src="<?php echo Yii::app()->request->baseUrl; ?>/img/topo02.png" />
		</div>
		<!-- final do conteudo direito -->
	</div>
	<div class="clear"></div>
</div>	

protected/views/layouts/home.php
<?php $this->renderPartial('/layouts/_header'); ?>

<div id="principal">
	<?php $this->renderPartial('/layouts/_topo'); ?>		
</div>

<div id="content">
	<?php echo $content; ?>					
</div>
	
<?php $this->renderPartial('/layouts/_footer'); ?>

protected/views/layouts/main.php
<?php $this->renderPartial('/layouts/_header'); ?>

<?php $this->renderPartial('/layouts/_topo'); ?>

<!-- inicia conteudo -->
<div id="container">
	<?php echo $content; ?>		
</div>
<!-- final conteudo -->
<div class="clear"></div>
	
<?php $this->renderPartial('/layouts/_footer'); ?>