protected/models/Anuncio.php
<?php

class Anuncio extends CActiveRecord
{
	public $s;
	
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}
	
	public function tableName()
	{
		return 'Anuncio';
	}
	
	public function rules()
	{
		return array(
			//array('titulo', 'required'),
			array('titulo, campo1Titulo, campo2Titulo, campo3Titulo, campo4Titulo, campo5Titulo, campo1Valor, campo2Valor, campo3Valor, campo4Valor, campo5Valor', 'length', 'max' => 64),
			array('img', 'file', 'types'=>'jpg, gif, png', 'allowEmpty' => true),
			array('conteudo', 'safe'),
			array('img', 'required', 'on' => 'tipo0'),
			array('titulo', 'required', 'on' => 'tipo1'),
			array('titulo, campo1Valor', 'required', 'on' => 'tipo2'),
			array('s', 'safe', 'on' => 'search')
		);
	}
	
	public function relations()
	{
		return array(
			'pagina' => array(self::BELONGS_TO, 'Pagina', 'paginaId'),
		);
	}
	
	public function attributeLabels()
	{
		return array(
			's' => 'Pesquisar',
			'id' => 'ID',
			'paginaId' => 'Pagina',
			'img' => 'Imagem',
			'titulo' => 'Título',
			'conteudo' => 'Conteúdo'
		);
	}
	
	public function isDestaque() {
		if ($this->tipo == 2) {
			$isDestaque = self::model()->find('tipo <> 2 AND titulo = :titulo', array(
				':titulo' => trim($this->titulo)
			));
		}
		return empty($isDestaque) ? false : true;
	}
	
	public function getImgUrl() {
		return $this->img ? Yii::app()->baseUrl . '/files/' . $this->img : '';		
	}
	
	public function getImgPath() {
		return $this->img ? Yii::app()->basePath . '/../files/' . $this->img : '';		
	}
	
	protected function beforeSave() {
		if (parent::beforeSave()) {
			
			// Verifica se o campo img recebeu algum upload.
			if (is_object($this->img)) {
				
				//Exclui a imagem antiga.
				if (is_file($this->imgPath)) unlink($this->imgPath);			
				
				// Define o nome do arquivo.					
				// $uploadedFileName = preg_replace('/[^a-z.]/', '', strtolower($this->img)); 
				$uploadedFileName = 'anuncio_' . $this->id . '.' . $this->img->extensionName;
				
				// Salva a imagem upada.
				$this->img->saveAs(Yii::app()->basePath . '/../files/' . $uploadedFileName);
				$this->img = $uploadedFileName;
			} else
				if (!is_file($this->imgPath)) 
					$this->img = null;
			
			return true;
		} else
			return false;
	}

	protected function afterDelete() {
		parent::afterDelete();
		
		if (is_file($this->imgPath)) unlink($this->imgPath);	
	}
		
	public function search()
	{
		$criteria = new CDbCriteria;
		
		$criteria->compare('titulo', $this->s, true, 'OR');
		
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort' => array(
				'defaultOrder' => 'titulo',
			)
		));
	}
}

protected/models/Pagina.php
<?php

class Pagina extends CActiveRecord
{
	public $s;
	
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}
	
	public function tableName()
	{
		return 'Pagina';
	}
	
	public function rules()
	{
		return array(
			array('titulo, nome', 'required'),
			array('titulo', 'length', 'max' => 64),
			array('nome', 'unique'),
			array('conteudo', 'safe'),
			array('s', 'safe', 'on' => 'search')
		);
	}
	
	public function relations()
	{
		return array(
			'anuncios' => array(self::HAS_MANY, 'Anuncio', 'paginaId'),
		);
	}
	
	public function attributeLabels()
	{
		return array(
			's' => 'Pesquisar',
			'id' => 'ID',
			'titulo' => 'Título',
			'conteudo' => 'Conteúdo'
		);
	}
	
	public function getUrl() {
		return Yii::app()->createUrl('/site/pagina', array('id' => $this->nome));
	}
		
	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('titulo', $this->s, true, 'OR');
		$criteria->compare('nome', $this->s, true, 'OR');

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort' => array(
				'defaultOrder' => 'nome'
			),
			'pagination' => array(
				'pageSize' => 20
			)
		));
	}
}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller 
{
	public function actionIndex() 
	{				
		$this->render('index');
	}
	
	public function actionIndice() 
	{
		$paginas = Pagina::model()->findAll(array('order' => 'titulo'));
		
		$this->render('indice', array(
			'paginas' => $paginas
		));
	}
		
	public function actionPagina($id) 
	{
		$pagina = Pagina::model()->findByAttributes(array('nome' => $id));
		
		if ($pagina === null)
			throw new CHttpException(404, 'A página solicitada não existe.');

		$anuncios = Anuncio::model()->with(array(
			'pagina' => array(
				'condition' => 'nome = :nome',
				'params' => array(
					':nome' => $pagina->nome
				)
			)
		))->findAll(array('order' => 'nome'));		
		
		$this->render('pagina', array(
			'pagina' => $pagina,
			'anuncios' => $anuncios
		));
	}
	
	public function actionConheca() 
	{
		$this->render('conheca');
	}
	
	public function actionUteis() 
	{
		$this->render('uteis');
	}
	
	public function actionAnuncie() 
	{		
		$model = new ContatoForm('anuncie');
		if(isset($_POST['ContatoForm']))
		{
			$model->attributes=$_POST['ContatoForm'];
			if($model->validate())
			{
				$from = Yii::app()->params['emailContato'];
				$headers  = "MIME-Version: 1.0\r\n";
				$headers .= "Content-Type: text/html; charset=utf-8\r\n";
				$headers .= "From: {$from}\r\n";
				$headers .= "Reply-To: {$model->email}\r\n";
				$headers .= "Return-Path: {$from}\r\n";
				$body  = "<style>";
				$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
				$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
				$body .= "th { width: 140px; text-align: left; }";
				$body .= "</style>";
				$body .= "<table>";
				$body .= "<tr>";
				$body .= "<th>{$model->getAttributeLabel('nome')}:</th>";
				$body .= "<td>{$model->nome}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('area')}:</th>";
				$body .= "<td>{$model->area}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('contato')}:</th>";
				$body .= "<td>{$model->contato}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('telefone')}:</th>";
				$body .= "<td>{$model->telefone}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('email')}:</th>";
				$body .= "<td>{$model->email}</td>";
				$body .= "</tr>";
				$body .= "</table>";
				
				mail($from, 'Site > Anuncie', $body, $headers, "-r" . $from);
				Yii::app()->user->setFlash('contatoForm', 'Obrigado por entrar em contato. Responderemos sua mensagem o mais breve possível.');
				$this->refresh();
			}
		}
		
		$this->render('anuncie', array(
			'model' => $model
		));
	}

	public function actionCadastro() 
	{		
		$model = new ContatoForm('cadastro');
		if(isset($_POST['ContatoForm']))
		{
			$model->attributes=$_POST['ContatoForm'];
			if($model->validate())
			{
				$from = Yii::app()->params['emailContato'];
				$headers  = "MIME-Version: 1.0\r\n";
				$headers .= "Content-Type: text/html; charset=utf-8\r\n";
				$headers .= "From: {$from}\r\n";
				$headers .= "Reply-To: {$model->email}\r\n";
				$headers .= "Return-Path: {$from}\r\n";
				$body  = "<style>";
				$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
				$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
				$body .= "th { width: 140px; text-align: left; }";
				$body .= "</style>";
				$body .= "<table>";
				$body .= "<tr>";
				$body .= "<th>{$model->getAttributeLabel('nome')}:</th>";
				$body .= "<td>{$model->nome}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('area')}:</th>";
				$body .= "<td>{$model->area}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('contato')}:</th>";
				$body .= "<td>{$model->contato}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('telefone')}:</th>";
				$body .= "<td>{$model->telefone}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('email')}:</th>";
				$body .= "<td>{$model->email}</td>";
				$body .= "</tr>";
				$body .= "</table>";
				
				mail($from, 'Site > Cadastro', $body, $headers, "-r" . $from);
				Yii::app()->user->setFlash('contatoForm', 'Obrigado por entrar em contato. Responderemos sua mensagem o mais breve possível.');
				$this->refresh();
			}
		}
		
		$this->render('cadastro', array(
			'model' => $model
		));
	}
	
	public function actionContato() 
	{		
		$model = new ContatoForm('contato');
		if(isset($_POST['ContatoForm']))
		{
			$model->attributes=$_POST['ContatoForm'];
			if($model->validate())
			{
				$from = Yii::app()->params['emailContato'];
				$headers  = "MIME-Version: 1.0\r\n";
				$headers .= "Content-Type: text/html; charset=utf-8\r\n";
				$headers .= "From: {$from}\r\n";
				$headers .= "Reply-To: {$model->email}\r\n";
				$headers .= "Return-Path: {$from}\r\n";
				$body  = "<style>";
				$body .= "table { width: 100%; font: normal 13px/20px Arial, sans-serif; }";
				$body .= "th, td { padding: 4px 8px; border-bottom: 1px solid #ddd; }";
				$body .= "th { width: 140px; text-align: left; }";
				$body .= "</style>";
				$body .= "<table>";
				$body .= "<tr>";
				$body .= "<th>{$model->getAttributeLabel('nome')}:</th>";
				$body .= "<td>{$model->nome}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('contato')}:</th>";
				$body .= "<td>{$model->contato}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('telefone')}:</th>";
				$body .= "<td>{$model->telefone}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('email')}:</th>";
				$body .= "<td>{$model->email}</td>";
				$body .= "</tr><tr>";
				$body .= "<th>{$model->getAttributeLabel('mensagem')}:</th>";
				$body .= "<td>{$model->mensagem}</td>";
				$body .= "</tr>";
				$body .= "</table>";
				
				mail($from, 'Site > Contato', $body, $headers, "-r" . $from);
				Yii::app()->user->setFlash('contatoForm', 'Obrigado por entrar em contato. Responderemos sua mensagem o mais breve possível.');
				$this->refresh();
			}
		}
		
		$this->render('contato', array(
			'model' => $model
		));
	}
	
	public function actionError() 
	{
		if ($error = Yii::app()->errorHandler->error) 
		{
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
}

protected/views/site/_compartilhar.php
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
	<a class="addthis_button_google_plusone" g:plusone:size="medium"></a> 
	<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
	<a class="addthis_button_tweet"></a>
	<a class="addthis_button_email btn btn-small">E-mail</a>
</div>
<!-- AddThis Button END -->	

protected/views/site/_searchForm.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'searchForm',
	'type' => 'search',
	'action' => !empty($action) ? $action : Yii::app()->createUrl($this->route),
	//'method' => 'get'
)); ?>

<?php echo $form->textFieldRow($model, 's', array('class' => 'search-query')); ?>

<?php $this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'submit',
	'label' => 'OK'
)); ?>

<?php $this->endWidget(); ?>

protected/views/site/anuncie.php
<?php $this->pageTitle = 'Quero Anunciar'; ?>

<h2>Quero Anunciar</h2>

<div id="container-conteudo">
	<?php if(Yii::app()->user->hasFlash('contatoForm')): ?>
	
	<p class="flash-success">
		<?php echo Yii::app()->user->getFlash('contatoForm'); ?>
	</p>
	
	<?php else: ?>
	
	<p class="chamada">Para anunciar no FoneFácil edição 
	<?php echo date('Y'); ?>, preencha os campos abaixo e aguarde o contato <br />
	de nossos representantes quando as vendas dos espaços publicitários forem iniciadas.</p>
	
	<?php $form = $this->beginWidget('CActiveForm'); ?>
	
	<?php echo $form->labelEx($model, 'nome'); ?>
	<?php echo $form->textField($model, 'nome'); ?>

	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'area'); ?>
	<?php echo $form->textField($model, 'area'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'contato'); ?>
	<?php echo $form->textField($model, 'contato'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'telefone'); ?>
	<?php echo $form->textField($model, 'telefone'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'email'); ?>
	<?php echo $form->textField($model, 'email'); ?>
	
	<div class="clear"></div>

	<?php echo CHtml::submitButton('Enviar', array('class' => 'botao')); ?>

	<?php $this->endWidget(); ?>
	
	<?php endif; ?>
</div>

protected/views/site/cadastro.php
<?php $this->pageTitle = 'Cadastre sua Empresa'; ?>

<h2>Cadastre sua Empresa</h2>

<div id="container-conteudo">
	<?php if(Yii::app()->user->hasFlash('contatoForm')): ?>
	
	<p class="flash-success">
		<?php echo Yii::app()->user->getFlash('contatoForm'); ?>
	</p>
	
	<?php else: ?>
	
	<p class="chamada">Se você deseja atualizar ou incluir seu comércio, indústria ou serviço <br />
	gratuitamente na Listagem da edição <?php echo date('Y'); ?>, preencha o formulário abaixo.</p>
	
	<?php $form = $this->beginWidget('CActiveForm'); ?>
	
	<?php echo $form->labelEx($model, 'nome'); ?>
	<?php echo $form->textField($model, 'nome'); ?>

	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'area'); ?>
	<?php echo $form->textField($model, 'area'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'contato'); ?>
	<?php echo $form->textField($model, 'contato'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'telefone'); ?>
	<?php echo $form->textField($model, 'telefone'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'email'); ?>
	<?php echo $form->textField($model, 'email'); ?>
	
	<div class="clear"></div>

	<?php echo CHtml::submitButton('Enviar', array('class' => 'botao')); ?>

	<?php $this->endWidget(); ?>
	
	<?php endif; ?>
</div>

protected/views/site/conheca.php
<?php $this->pageTitle = 'Conheça o FoneFácil'; ?>

<h2>Conheça o FoneFácil</h2>

<img class="img-2" src="<?php echo Yii::app()->request->baseUrl; ?>/img/capa_2010.jpg" />

<div id="container-conteudo">
	<p class="chamada">Criado para divulgar Salto para Salto e estimular seu crescimento, o FoneFácil é um instrumento indispensável para cotações, disque-entregas e buscas em geral. Anunciando no FoneFácil,sua empresa é divulgada no catálogo impresso e na internet. FoneFácil, o Catálogo Oficial da ACIAS.</p>
	<strong>Como funciona</strong>
	<p>O FoneFácil possui as páginas divididas por ramo de atividade e seus anúncios são apresentados de maneira clara, objetiva e padronizada. Além disso, o catálogo conta com índice completo e por anunciante, que auxilia as consultas. </p>
	<br />
	<strong>Conteúdo</strong>
	<p>São mais de 2.500 empresas e profissionais, com seus telefones organizados e atualizados, telefones úteis, horários de ônibus, guia de médicos Unimed e muito mais.</p>
	<br />
	<strong>Tiragem</strong>
	<p>A tiragem do catálogo é de 20.000 exemplares e a distribuição é gratuita.</p>
	<br />
	<strong>Quem Produz</strong>
	<p>O FoneFácil é produzido pela Agência Layout e editado pela Editora Minelli Brasil.</p>
	<br />
	<strong>Apoio</strong>
	<p>As empresas abaixo apóiam a edição 2010 do FoneFácil:</p>
	<img class="img-4" src="<?php echo Yii::app()->request->baseUrl; ?>/img/logos_apoio.jpg" />
</div>

protected/views/site/contato.php
<?php $this->pageTitle = 'Contato'; ?>

<h2>Contato</h2>

<div id="container-conteudo">
	<?php if(Yii::app()->user->hasFlash('contatoForm')): ?>
	
	<p class="flash-success">
		<?php echo Yii::app()->user->getFlash('contatoForm'); ?>
	</p>
	
	<?php else: ?>
	
	<p class="chamada">Esse é um espaço para você tirar suas dúvidas e fazer qualquer sugestão ou crítica.<br />
	Para isso, preencha o formulário abaixo e em breve entraremos em contato.</p>

	<p><strong>Fones:</strong> 11 4021.4421 / 11 4456.6959<br />
	<strong>Financeiro:</strong> <a href="mailto:eliana@layoutnet.com.br">eliana@layoutnet.com.br</a><br />
	<strong>Propaganda:</strong> <a href="mailto:claudio@layoutnet.com.br">claudio@layoutnet.com.br</a><br />
	<strong>Layout:</strong> Rua Henrique Viscardi, 1303 - Jd. Celani - Salto/SP</p>

	<br />
	
	<?php $form = $this->beginWidget('CActiveForm'); ?>
	
	<?php echo $form->labelEx($model, 'nome'); ?>
	<?php echo $form->textField($model, 'nome'); ?>

	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'contato'); ?>
	<?php echo $form->textField($model, 'contato'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'telefone'); ?>
	<?php echo $form->textField($model, 'telefone'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'email'); ?>
	<?php echo $form->textField($model, 'email'); ?>
	
	<div class="clear"></div>

	<?php echo $form->labelEx($model, 'mensagem'); ?>
	<?php echo $form->textArea($model, 'mensagem'); ?>
	
	<div class="clear"></div>

	<?php echo CHtml::submitButton('Enviar', array('class' => 'botao')); ?>

	<?php $this->endWidget(); ?>
	
	<?php endif; ?>
</div>

protected/views/site/error.php
<?php $this->pageTitle = 'Erro'; ?>

<h2>Erro <?php echo $code ?></h2>

<div id="container-conteudo">
	<p><?php echo CHtml::encode($message) ?></p>
</div>

protected/views/site/index.php
<?php 
$this->pageTitle = ''; 
$this->layout = 'home';
?>

protected/views/site/indice.php
<?php $this->pageTitle = 'Índice Anunciates'; ?>

<h2>Índice Anunciates</h2>

<div id="container-conteudo">
	<p class="chamada">AGRADECEMOS PELA CONFIANÇA E POR ACREDITAREM EM NOSSO TRABALHO. 
	FICAMOS SATISFEITOS EM SABER QUE O FONEFÁCIL PODE CONTRIBUIR COM O CRESCIMENTO DE 
	SUA EMPRESA E DE NOSSA CIDADE. MUITO OBRIGADO.</p>
	
	<ul class="anunciantes">
		<?php foreach ($paginas as $pagina) : ?>
			<li><?php echo CHtml::link($pagina->titulo, $pagina->url) ; ?></li>	
		<?php endforeach; ?>	
	</ul>
</div>

protected/views/site/pagina.php
<?php $this->pageTitle = CHtml::encode($pagina->titulo); ?>

<h2><?php echo $this->pageTitle; ?></h2>

<div id="container-conteudo">
	<!-- propaganda menor -->
	
		<?php foreach ($anuncios as $anuncio) : ?>
			<?php if ($anuncio->tipo == 1) : ?>	
			<div class="propaganda-menor">		
				<?php echo CHtml::image($anuncio->imgUrl, null); ?>
				<div class="segura-texto">
					<h3><?php echo CHtml::encode($anuncio->titulo); ?></h3>
					<p><?php echo $anuncio->conteudo; ?></p>
					<br />
					<ul>
						<?php if ($anuncio->campo1Titulo && $anuncio->campo1Valor) : ?>
							<li><strong><?php echo CHtml::encode($anuncio->campo1Titulo); ?>:</strong> <?php echo CHtml::encode($anuncio->campo1Valor); ?></li>
						<?php endif; ?>
						<?php if ($anuncio->campo2Titulo && $anuncio->campo2Valor) : ?>
							<li><strong><?php echo CHtml::encode($anuncio->campo2Titulo); ?>:</strong> <?php echo CHtml::encode($anuncio->campo2Valor); ?></li>
						<?php endif; ?>
						<?php if ($anuncio->campo1Titulo && $anuncio->campo3Valor) : ?>
							<li><strong><?php echo CHtml::encode($anuncio->campo3Titulo); ?>:</strong> <?php echo CHtml::encode($anuncio->campo3Valor); ?></li>
						<?php endif; ?>
						<?php if ($anuncio->campo1Titulo && $anuncio->campo4Valor) : ?>
							<li><strong><?php echo CHtml::encode($anuncio->campo4Titulo); ?>:</strong> <?php echo CHtml::encode($anuncio->campo4Valor); ?></li>
						<?php endif; ?>
						<?php if ($anuncio->campo1Titulo && $anuncio->campo5Valor) : ?>
							<li><strong><?php echo CHtml::encode($anuncio->campo5Titulo); ?>:</strong> <?php echo CHtml::encode($anuncio->campo5Valor); ?></li>
						<?php endif; ?>
					</ul>
				</div>
				<div class="clear"></div>
			</div>
			<?php endif; ?>	
		<?php endforeach; ?>			
	
	
	<!-- propaganda maior -->
	
		<?php foreach ($anuncios as $anuncio) : ?>
			<?php if ($anuncio->tipo == 0 && $anuncio->img) : ?>	
			<div class="propaganda-maior">
				<?php echo CHtml::image($anuncio->imgUrl, null); ?>
			</div>	
			<?php endif; ?>	
		<?php endforeach; ?>
		
	
	<!-- inicio agenda -->
	<div class="lista">
		<ul>
			<?php foreach ($anuncios as $anuncio) : ?>
				<?php if ($anuncio->tipo == 2) : ?>						
					<li>
						<?php echo $anuncio->isDestaque() ? '<strong>' : ''; ?>
						<h4><?php echo CHtml::encode($anuncio->titulo); ?></h4>
						<span><?php echo CHtml::encode($anuncio->campo1Valor); ?></span>
						<?php echo $anuncio->isDestaque() ? '</strong>' : ''; ?>
					</li>
				<?php endif; ?>	
			<?php endforeach; ?>			
		</ul>
	</div>				
</div>	