protected/admin/controllers/HomeController.php
<?php

class HomeController extends Controller
{
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'users' => array('@')
			),
			array(
				'allow',
				'actions' => array('error', 'login'),
				'users' => array('*')
			),
			array('deny')
		);
	}
		
	public function actionIndex()
	{
		$this->redirect(Yii::app()->createUrl('pagina'));
	}
	
	public function actionError()
	{
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}
	
	public function actionLogin()
	{
		$model = new LoginForm;
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'loginForm') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
		
		if (isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			if ($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		
		$this->render('login', array(
			'model' => $model
		));
	}
	
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	public function actionAlterarSenha($id = null)
	{
		if (!$id) 
			$id = Yii::app()->user->id;
			
		$model = Usuario::model()->findByPk($id);
		
		if ($model === null)
			throw new CHttpException(404, 'A página solicitada não existe.');
		
		$model->setScenario('alterarSenha');
		
		if (Yii::app()->request->urlReferrer !== Yii::app()->request->hostInfo . Yii::app()->request->requestUri)
			Yii::app()->user->setReturnUrl(Yii::app()->request->urlReferrer);
		
		if (isset($_POST['Usuario'])) {
			$model->attributes = $_POST['Usuario'];
			
			if ($model->save()) {
				Yii::app()->user->setFlash('sucess', '<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		
		$this->render('alterarSenha', array('model' => $model));
	}
	
}

protected/admin/controllers/PaginaController.php
<?php

class PaginaController extends Controller
{
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'users' => array('@')
			),
			array('deny')
		);
	}
	
	public function actionIncluirAnuncio($pagina, $tipo)
	{
		$pagina = $this->loadModel($pagina);
			
		$anuncio = new Anuncio;
		$anuncio->paginaId = $pagina->id;
		$anuncio->tipo = $tipo;
		$anuncio->save();
	}
	
	public function actionRemoverAnuncio($id)
	{
		Anuncio::model()->findByPk($id)->delete();
		
		Yii::app()->end();
	}
	
	public function actionIndex()
	{
		$model = new Pagina('search');
		$model->unsetAttributes();
		
		if (isset($_GET['Pagina']))
			$model->setAttributes($_GET['Pagina']);
		
		$this->render('index', array(
			'model' => $model
		));
	}
	
	public function actionCreate()
	{
		$model = new Pagina;
		
		$this->performAjaxValidation($model);
	
		if (isset($_POST['Pagina'])) {
			$model->setAttributes($_POST['Pagina']);
			
			if ($model->save()) {
				Yii::app()->user->setFlash('success', '<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');
				$this->redirect(array('update', 'id' => $model->id));
			}
		}
		
		$this->render('create', array(
			'model' => $model
		));
	}
	
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);
		
		$this->performAjaxValidation($model);
	
		if (isset($_POST['Pagina'])) {
			$model->setAttributes($_POST['Pagina']);
			
			if ($model->save()) {
				Yii::app()->user->setFlash('success', '<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');
				$this->refresh();
			}
		}
		
		$this->render('update', array(
			'model' => $model
		));
	}
	
	public function actionAnuncios($id)
	{
		$model = $this->loadModel($id);
		
		$this->performAjaxValidation($model);
		
		$anunciosPorTipo = array(
			0 => Anuncio::model()->findAll(array(
					'index' => 'id', 
					'condition' => 'tipo = 0 AND paginaId = :paginaId', 
					'params' => array(':paginaId' => $model->id)
				)
			),
			1 => Anuncio::model()->findAll(array(
					'index' => 'id', 
					'condition' => 'tipo = 1 AND paginaId = :paginaId', 
					'params' => array(':paginaId' => $model->id)
				)
			),
			2 => Anuncio::model()->findAll(array(
					'index' => 'id', 
					'condition' => 'tipo = 2 AND paginaId = :paginaId', 
					'params' => array(':paginaId' => $model->id)
				)
			)
		);
		
		foreach ($anunciosPorTipo as $i => $anuncios) {
			foreach ($anuncios as $ii => $anuncio) {
				$anunciosPorTipo[$i][$ii]->setScenario('tipo' . $anuncio->tipo); 	
			}
		}
		
		if (isset($_POST['Pagina'])) {
			$model->setAttributes($_POST['Pagina']);
			
			if (empty($_POST['Pagina']['participantes']))
				$model->participantes = null;
						
			if ($model->save()) {
				Yii::app()->user->setFlash('success', '<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');
				$this->refresh();
			}
		}
				
	    if (isset($_POST['Anuncio'])) {
	    	foreach ($anunciosPorTipo as $i => $anuncios) {
		        foreach($anuncios as $ii => $anuncio) {
					if (isset($_POST['Anuncio'][$ii])) {
						$uploadedFile = CUploadedFile::getInstance(Anuncio::model(), "[$ii]img");
						$anunciosPorTipo[$i][$ii]->setAttributes($_POST['Anuncio'][$ii]);
						if ($uploadedFile)
							$anunciosPorTipo[$i][$ii]->img = $uploadedFile;					
						$anunciosPorTipo[$i][$ii]->save();
					}
				}			
			}
	    }
				
		$this->render('anuncios', array(
			'model' => $model,
			'anuncios' => $anunciosPorTipo
		));
	}
	
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			$this->loadModel($id)->delete();
			$this->redirect(array('index'));
		} else
			throw new CHttpException(400, 'Solicitação inválida. Por favor, não repita esta solicitação novamente.');
	}
	
	public function loadModel($id)
	{
		$model = Pagina::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'A página solicitada não existe.');
		return $model;
	}
	
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'paginaForm') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
}

protected/admin/controllers/UsuarioController.php
<?php

class UsuarioController extends Controller
{		
	public function accessRules()
	{
		return array(
			array(
				'allow',
				'users' => array('*'),
				'expression' => 'isset($user->nivelAcesso) && ($user->nivelAcesso >= Usuario::NIVEL_ACESSO_ADMIN)'
			),
			array(
				'allow',
				'users' => array('alterarSenha')
			),
			array('deny')
		);
	}
	
	public function actionIndex()
	{
		$model = new Usuario('search');
		$model->unsetAttributes();
		
		if (isset($_GET['Usuario']))
			$model->setAttributes($_GET['Usuario']);
		
		$this->render('index', array(
			'model' => $model
		));
	}
	
	public function actionCreate()
	{
		$model = new Usuario;
	
		if (isset($_POST['Usuario'])) {
			$model->setAttributes($_POST['Usuario']);
			
			if ($model->save()) {
				Yii::app()->user->setFlash('success', '<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');
				$this->redirect(array('update', 'id' => $model->id));
			}
		}
		
		$this->render('create', array(
			'model' => $model
		));
	}
	
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);
		
		if (isset($_POST['Usuario'])) {
			$model->setAttributes($_POST['Usuario']);
			
			if ($model->save()) {
				Yii::app()->user->setFlash('success', '<strong>Sucesso!</strong> As alterações foram salvas com sucesso.');
				$this->refresh();
			}
		}
		
		$this->render('update', array(
			'model' => $model
		));
	}
	
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			$this->loadModel($id)->delete();
			$this->redirect(array('index'));
		} else
			throw new CHttpException(400, 'Solicitação inválida. Por favor, não repita esta solicitação novamente.');
	}
	
	public function loadModel($id)
	{
		$model = Usuario::model()->findByPk($id);
		if ($model === null)
			throw new CHttpException(404, 'A página solicitada não existe.');
		return $model;
	}
	
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'usuarioForm') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
}

protected/admin/views/home/alterarSenha.php
<?php 
$this->pageTitle = 'Usuário';
$this->pageSubtitle = '/ Alterar senha';
$this->menu = array(
	array(
		'class' => 'bootstrap.widgets.TbMenu',
		'items' => array(
			array(
				'label' => 'Voltar',
				'icon' => 'arrow-left',
				'url' => Yii::app()->user->returnUrl,
			)
		)
	)
); ?>

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id' => 'usuarioAlterarSenhaForm',
	'type' => 'horizontal',
	'enableClientValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true
	)
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->passwordFieldRow($model, 'novaSenha', array('class' => 'span')); ?>

<?php echo $form->passwordFieldRow($model, 'novaSenhaRepeat', array('class'=>'span')); ?>

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'buttonType' => 'submit',
		'label' => 'Salvar',
		'icon' => 'ok white',
		'type' => 'primary'
	)); ?>

	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'label' => 'Cancelar',
		'type' => 'link',
		'url' => Yii::app()->user->returnUrl
	)); ?>
</div>
	
<?php $this->endWidget(); ?>

protected/admin/views/home/error.php
<?php $this->pageTitle = 'Erro ' . $code; ?>

<p class="error alert alert-error"><?php echo CHtml::encode($message); ?></p> 

protected/admin/views/home/login.php
<?php $this->pageTitle = 'Login'; ?>

<?php echo CHtml::error($model, 'username', array('class' => 'alert alert-block alert-error')); ?>

<?php echo CHtml::error($model, 'password', array('class' => 'alert alert-block alert-error')); ?>				

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'loginForm',
	'enableClientValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true
	)
)); ?>

<?php echo $form->labelEx($model, 'username'); ?>

<?php echo $form->textField($model, 'username', array('class' => 'input-block-level')); ?>

<?php echo $form->labelEx($model, 'password'); ?>

<?php echo $form->passwordField($model, 'password', array('class' => 'input-block-level')); ?>

<div class="form-actions">
 	<label class="checkbox pull-left">
    	<?php echo $form->checkBox($model, 'rememberMe'); ?>
    	<?php echo $model->getAttributeLabel('rememberMe'); ?>
	</label>
	
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'buttonType' => 'submit',
		'label' => 'Entrar',
		'type' => 'primary',
		'htmlOptions' => array(
			'class' => 'pull-right'
		)
	)); ?>
</div>

<?php $this->endWidget(); ?>

protected/admin/views/layouts/main.php
<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="pt-BR" />
	<title><?php echo Yii::app()->name; ?> | <?php echo CHtml::encode($this->pageTitle); ?></title>
 
	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/admin/bootstrap.css'); ?>
	<?php Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl . '/css/admin/main.css'); ?>	

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body class="<?php echo $this->id . ' ' . $this->action->id; ?>">
	
<?php if (!Yii::app()->user->isGuest) : ?>
	
<?php $this->widget('bootstrap.widgets.TbNavbar', array(
	'fixed' => 'top',
	'brand' => CHtml::encode(Yii::app()->name),
	'brandUrl' => Yii::app()->createUrl('home/index'),
	'collapse' => true,
	'type' => 'inverse',
	'items' => array(
		array(
			'class' => 'bootstrap.widgets.TbMenu',
			'items' => array(
				array(
					'label' => 'Páginas',
					'url' => array('/pagina'),
				),
				array(
					'label' => 'Usuários',
					'url' => array('/usuario'),
					'visible' => Yii::app()->user->nivelAcesso >= Usuario::NIVEL_ACESSO_ADMIN
				)
			)
		),
		array(
			'class' => 'bootstrap.widgets.TbMenu',
			'htmlOptions' => array(
				'class' => 'pull-right'
			),
			'items' => array(
				array(
					'label' => 'Ir para o site',
					'url' => Yii::app()->request->hostInfo . Yii::app()->request->baseUrl
				),
				array(
					'label' => Yii::app()->user->name,
					'items' => array(
						array(
							'label' => 'Alterar senha',
							'url' => array('/home/alterarSenha')
						),
						'---',
						array(
							'label' => 'Sair',
							'url' => array('/home/logout'),
						)						
					)
				)

			)
		)
	)
)); ?>

<?php if (!empty($this->menu)) : ?>

<div id="menu">
	<?php $this->widget('bootstrap.widgets.TbNavbar', array(
		'fixed' => 'top',
		'brand' => false,
		'items' => $this->menu
	)); ?>
</div><!-- menu -->

<?php endif; ?>	
	
<?php endif; ?>	

<div class="container" id="page">
	<div class="page-header">
		<h2><?php echo $this->pageTitle; ?> <small><?php echo $this->pageSubtitle; ?></small></h2>
	</div>
	
	<?php if(Yii::app()->user->hasFlash('success')): ?>
	<p class="flash alert alert-success"><?php echo Yii::app()->user->getFlash('success'); ?></p>
	<?php endif; ?>
	
	<?php if(Yii::app()->user->hasFlash('error')): ?>
	<p class="flash alert alert-error"><?php echo Yii::app()->user->getFlash('error'); ?></p>
	<?php endif; ?>
	
	<?php if(Yii::app()->user->hasFlash('info')): ?>
	<p class="flash alert alert-info"><?php echo Yii::app()->user->getFlash('info'); ?></p>
	<?php endif; ?>
	
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div><!-- page -->

<div id="ajax-loading"></div>

<?php Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/admin/main.js'); ?>

</body>
</html>

protected/admin/views/pagina/_anuncioTipo0ListItem.php
<tr<?php echo $form->errorSummary($data) ? ' class="error"' : ''; ?>>
	<td><h4 style="margin: 0">#<?php echo $index + 1; ?></h4></td>

	<td>
		<?php if ($data->imgUrl) : ?>
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'link',
			'icon' => 'eye-open',
			'url' => $data->imgUrl,
			'size' => 'small',
			'htmlOptions' => array(
				'rel' => 'tooltip',
				'title' => 'Visualizar',
				'target' => '_blank'
			)
		)); ?>			
		<?php endif; ?>
	</td>
	
	<td><?php echo $form->fileField($data, "[$data->id]img"); ?></td>
	
	<td><?php echo $form->errorSummary($data, '', '', array('class' => false)); ?></td>
	
	<td>
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'url' => '#',
			'type' => 'danger',
			'icon' => 'trash white',
			'size' => 'small',
			'htmlOptions' => array(
				'rel' => 'tooltip',
				'title' => 'Excluir',
				'class' => 'btn-delete'
			)
		)); ?>				
	</td>
	<td style="display: none;" class="id"><?php echo $data->id; ?></td>
</tr>

<?php 
$url = $this->createUrl('removerAnuncio');
$js = <<<EOD
$('.list-view .btn-delete').live('click', function(e) {
	var id = $(this).parents('tr').children('td.id').text().trim();
	jQuery.ajax({
		'success': function() { 
			$.fn.yiiListView.update('paginaAnuncioTipo0List'); 
		},
		'url': '$url&id='+id,
		'cache': false
	});
	e.preventDefault();
});
EOD;
Yii::app()->clientScript->registerScript('paginaAnunciosTipo0', $js); ?>

protected/admin/views/pagina/_anuncioTipo1ListItem.php
<tr<?php echo $form->errorSummary($data) ? ' class="error"' : ''; ?>>
	<td><h4 style="margin: 0">#<?php echo $index + 1; ?></h4></td>
	
	<td>
		<table class="table">		
			<tr>
				<th><?php echo $form->labelEx($data, "[$data->id]img"); ?></th>
				<td>
					<?php if ($data->imgUrl) : ?>
					<?php $this->widget('bootstrap.widgets.TbButton', array(
						'buttonType' => 'link',
						'icon' => 'eye-open',
						'url' => $data->imgUrl,
						'size' => 'small',
						'htmlOptions' => array(
							'rel' => 'tooltip',
							'title' => 'Visualizar',
							'target' => '_blank'
						)
					)); ?>			
					<?php endif; ?>
					<?php echo $form->fileField($data, "[$data->id]img"); ?>
				</td>
			</tr>
			<tr>
				<th><?php echo $form->labelEx($data, "[$data->id]titulo"); ?></th>
				<td><?php echo $form->textField($data, "[$data->id]titulo", array('class' => 'input-block-level')); ?></td>
			</tr>
			<tr>
				<th><?php echo $form->labelEx($data, "[$data->id]conteudo"); ?></th>
				<td><?php echo $form->textArea($data, "[$data->id]conteudo", array('class' => 'input-block-level')); ?>	</td>		
			</tr>
			<tr>
				<th><?php echo $form->textField($data, "[$data->id]campo1Titulo", array('class' => 'input-block-level')); ?></th>
				<td><?php echo $form->textField($data, "[$data->id]campo1Valor", array('class' => 'input-block-level')); ?></td>		
			</tr>
			<tr>
				<th><?php echo $form->textField($data, "[$data->id]campo2Titulo", array('class' => 'input-block-level')); ?></th>
				<td><?php echo $form->textField($data, "[$data->id]campo2Valor", array('class' => 'input-block-level')); ?></td>		
			</tr>	
			<tr>
				<th><?php echo $form->textField($data, "[$data->id]campo3Titulo", array('class' => 'input-block-level')); ?></th>
				<td><?php echo $form->textField($data, "[$data->id]campo3Valor", array('class' => 'input-block-level')); ?></td>		
			</tr>	
			<tr>
				<th><?php echo $form->textField($data, "[$data->id]campo4Titulo", array('class' => 'input-block-level')); ?></th>
				<td><?php echo $form->textField($data, "[$data->id]campo4Valor", array('class' => 'input-block-level')); ?></td>		
			</tr>	
			<tr>
				<th><?php echo $form->textField($data, "[$data->id]campo5Titulo", array('class' => 'input-block-level')); ?></th>
				<td><?php echo $form->textField($data, "[$data->id]campo5Valor", array('class' => 'input-block-level')); ?></td>		
			</tr>						
		</table>
	</td>
	
	<td><?php echo $form->errorSummary($data, '', '', array('class' => false)); ?></td>
	
	<td>
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'url' => '#',
			'type' => 'danger',
			'icon' => 'trash white',
			'size' => 'small',
			'htmlOptions' => array(
				'rel' => 'tooltip',
				'title' => 'Excluir',
				'class' => 'btn-delete'
			)
		)); ?>				
	</td>
	<td style="display: none;" class="id"><?php echo $data->id; ?></td>
</tr>

<?php 
$url = $this->createUrl('removerAnuncio');
$js = <<<EOD
$('.list-view .btn-delete').live('click', function(e) {
	var id = $(this).parents('tr').children('td.id').text().trim();
	jQuery.ajax({
		'success': function() { 
			$.fn.yiiListView.update('paginaAnuncioTipo1List'); 
		},
		'url': '$url&id='+id,
		'cache': false
	});
	e.preventDefault();
});
EOD;
Yii::app()->clientScript->registerScript('paginaAnunciosTipo0', $js); ?>

protected/admin/views/pagina/_anuncioTipo2ListItem.php
<tr<?php echo $form->errorSummary($data) ? ' class="error"' : ''; ?>>
	<td><h4 style="margin: 0">#<?php echo $index + 1; ?></h4></td>
	
	<td><?php echo $form->textField($data, "[$data->id]titulo", array('class' => 'input-block-level')); ?></td>

	<td><?php echo $form->textField($data, "[$data->id]campo1Valor", array('class' => 'input-block-level')); ?></td>		
	
	<td><?php echo $form->errorSummary($data, '', '', array('class' => false)); ?></td>
	
	<td>
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'url' => '#',
			'type' => 'danger',
			'icon' => 'trash white',
			'size' => 'small',
			'htmlOptions' => array(
				'rel' => 'tooltip',
				'title' => 'Excluir',
				'class' => 'btn-delete'
			)
		)); ?>				
	</td>
	<td style="display: none;" class="id"><?php echo $data->id; ?></td>
</tr>

<?php 
$url = $this->createUrl('removerAnuncio');
$js = <<<EOD
$('.list-view .btn-delete').live('click', function(e) {
	var id = $(this).parents('tr').children('td.id').text().trim();
	jQuery.ajax({
		'success': function() { 
			$.fn.yiiListView.update('paginaAnuncioTipo0List'); 
		},
		'url': '$url&id='+id,
		'cache': false
	});
	e.preventDefault();
});
EOD;
Yii::app()->clientScript->registerScript('paginaAnunciosTipo2', $js); ?>

protected/admin/views/pagina/_form.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'paginaForm',
	'type' => 'horizontal'
)); ?>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldRow($model, 'titulo', array('class' => 'span4')); ?>

<?php echo $form->textFieldRow($model, 'nome', array('class' => 'span4')); ?>

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'buttonType' => 'submit',
		'label' => 'Salvar',
		'type' => 'primary',
		'icon' => 'ok white'
	)); ?> 
	
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'label' => 'Cancelar',
		'url' => $this->createUrl('index'),
		'type' => 'link'
	)); ?>
</div>
	
<?php $this->endWidget(); ?>

protected/admin/views/pagina/_searchForm.php
<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'paginaSearchForm',
	'type' => 'search',
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
	'htmlOptions' => array('class' => 'pull-right')
)); ?>

<?php echo $form->textFieldRow($model, 's', array('class' => 'search-query')); ?>

<?php $this->widget('bootstrap.widgets.TbButton', array(
    'buttonType' => 'submit',
	'icon' => 'search',
	'htmlOptions' => array(
		'data-title' => 'Pesquisar', 
		'rel' => 'tooltip'
	)
)); ?>
		
<?php $this->endWidget(); ?>

protected/admin/views/pagina/anuncios.php
<?php 
$this->pageTitle = 'Página';
$this->pageSubtitle = '/ Anúncios (' . CHtml::encode($model->titulo) . ')';
$this->menu = array(
	array(
		'class' => 'bootstrap.widgets.TbMenu',
		'items' => array(
			array(
				'label' => 'Voltar',
				'icon' => 'arrow-left',
				'url' => array('index'),
			),
			array(
				'label' => 'Incluir',
				'icon' => 'file',
				'url' => array('create')
			),
			array(
				'label' => 'Editar',
				'icon' => 'pencil',
				'url' => array('update', 'id' => $model->id)
			),			
			array(
				'label' => 'Excluir',
				'icon' => 'trash',
				'url' => '#',
				'linkOptions' => array(
					'submit' => array('delete', 'id' => $model->id),
					'confirm' => 'Tem certeza que deseja excluir este registro?'
				)
			)
		)
	)
); 

$tiposAnuncio = array(
	'Página Inteira', 'Padrão', 'Básico'
); 
?>

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id' => 'anuncioForm',
	'htmlOptions' => array('enctype' => 'multipart/form-data')
)); ?>

<?php foreach ($tiposAnuncio as $i => $tipoAnuncio) : ?>
	
<div class="panel">
	<div class="panel-header">
		<h3 class="panel-heading"><?php echo $tipoAnuncio; ?></h3>
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType' => 'ajaxLink',
			'type' => 'success',
			'size' => 'small',
			'icon' => 'plus white',
			'url' => $this->createUrl('incluirAnuncio', array('pagina' => $model->id, 'tipo' => $i)),
			'ajaxOptions' => array(		
				'success' => "js: function() {
					// $.fn.yiiListView.update('paginaAnuncioTipo{$i}List'); 
					location.reload();
				}",		
			),
			'htmlOptions' => array(
				'title' => 'Incluir',
				'rel' => 'tooltip'
			)
		)); ?>			
	</div>

	<?php $this->widget('bootstrap.widgets.TbListView', array(
		'id' => "paginaAnuncioTipo{$i}List",
		'itemView' => "_anuncioTipo{$i}ListItem",
		'template' => '<table class="table"><tbody>{items}</tbody></table>',
		'viewData' => array('form' => $form),
		'dataProvider' => new CArrayDataProvider($anuncios[$i], array(
			'pagination' => array(
				'pageSize' => 999999
			)
		)),
	)); ?>
</div>

<?php endforeach; ?>

<div class="form-actions">
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'buttonType' => 'submit',
		'label' => 'Salvar',
		'type' => 'primary',
		'icon' => 'ok white'
	)); ?> 
	
	<?php $this->widget('bootstrap.widgets.TbButton', array(
		'label' => 'Cancelar',
		'url' => $this->createUrl('index'),
		'type' => 'link'
	)); ?>
</div>
	
<?php $this->endWidget(); ?>